# Generated by Django 5.1.2 on 2024-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=20)),
                ('date_created', models.DateField()),
                ('own', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=20)),
                ('mortgage', models.CharField(max_length=20)),
                ('score', models.IntegerField(max_length=20)),
                ('apartment', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Apart_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adver_id', models.CharField(max_length=20)),
                ('image_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_app', models.IntegerField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('area', models.IntegerField(max_length=20)),
                ('room_quantity', models.IntegerField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('region_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Disrtict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictrict_name', models.CharField(max_length=20)),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adver', models.IntegerField(max_length=20)),
                ('eEmail', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('roleName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rolename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
